<table width="100%"  border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="5" class="film-nav-left"><img src="/films/images/navleft_img.jpg" width="5" height="5" alt="" /></td>
    <td><div id="filmsmainnav"><a href="/films/" title="Films home page">&nbsp;Home&nbsp;</a><a href="/films/aboutfilms.htm" title="About these films">&nbsp;About these films&nbsp;</a><a href="/films/1945to1951/" title="1945 - 1951">&nbsp;1945 - 1951&nbsp;</a><a href="/films/1951to1964/" title="1951 - 1964">&nbsp;1951 - 1964&nbsp;</a><a href="/films/1964to1979/" title="1964 - 1979">&nbsp;1964 - 1979&nbsp;</a><a href="/films/1979to2006/" title="1979 - 2006">&nbsp;1979 - 2006&nbsp;</a><a href="/films/view_all_films.htm" title="View all films" class="highlighted">&nbsp;View all films&nbsp;</a><a href="/films/downloads.htm" title="Downloads">&nbsp;Downloads&nbsp;</a></div></td>
    <td width="6" class="film-nav-right"><img src="/films/images/navright_img.jpg" width="6" height="5" alt="" /></td>
  </tr>
</table>